<?php
$PATH =  [
    'CERTS' =>  __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'certs' . DIRECTORY_SEPARATOR,
    'KEYS' => __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'key' . DIRECTORY_SEPARATOR,
    'WSDL' => __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'wsdl' . DIRECTORY_SEPARATOR,
    'XSL' => __DIR__ . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR . 'xsl' . DIRECTORY_SEPARATOR,
];

return [
    'SOAP' => __DIR__ . DIRECTORY_SEPARATOR,
    'CLIENT' =>  $PATH['CERTS'] . 'SDI-01174380053_client.pem',
    'SERVER' => $PATH['CERTS'] . 'SDI-01174380053_server.pem',
    'KEYFILE' => $PATH['KEYS'] . 'fatturapa.key',
    'EndPointRicevi' => 'https://servizi.fatturapa.it/ricevi_file',
    'EndPointRiceviNotifica' => 'https://servizi.fatturapa.it/ricevi_notifica',
    'CA_AdE' => $PATH['CERTS'] . 'CA_AdE_All.crt',
    'TestEndPointRicevi' => 'https://testservizi.fatturapa.it/ricevi_file',
    'TestEndPointRiceviNotifica' => 'https://testservizi.fatturapa.it/ricevi_notifica',
    'TestCA_AdE' => $PATH['CERTS'] . 'CA_AdE_Test_All.pem',
    'SdIRiceviFile' => $PATH['WSDL'] . 'SdIRiceviFile_v1.0.wsdl',
    'SdITrasmissione' => $PATH['WSDL'] . 'TrasmissioneFatture_v1.1.wsdl',
    'SdIRicezione' => $PATH['WSDL'] . 'RicezioneFatture_v1.0.wsdl',
    'SdIRiceviNotifica' => $PATH['WSDL'] . 'SdIRiceviNotifica_v1.0.wsdl',
    'SdIRicezioneTypes_v10' => $PATH['WSDL'] . 'RicezioneTypes_v1.0.xsd',
    'SdIRicezioneTypes_v101' => $PATH['WSDL'] . 'RicezioneTypes_v1.0_1.xsd',
    'TrasmissioneTypes_v10' => $PATH['WSDL'] . 'TrasmissioneTypes_v1.0.xsd',
    'TrasmissioneTypes_v11' => $PATH['WSDL'] . 'TrasmissioneTypes_v1.1.xsd',
    'StyleSheetPR' => $PATH['XSL'] . 'fatturaordinaria_v1.2.1.xsl',
    'StyleSheetPA' => $PATH['XSL'] . 'fatturaPA_v1.2.1.xsl',
    'StyleSheetAS' => $PATH['XSL'] . 'FoglioStileAssoSoftware.xsl',
    'StyleSheetAT' => $PATH['XSL'] . 'AT_v1.0.xsl',
    'StyleSheetDT' => $PATH['XSL'] . 'DT_v1.0.xsl',
    'StyleSheetMC' => $PATH['XSL'] . 'MC_v1.0.xsl',
    'StyleSheetMT' => $PATH['XSL'] . 'MT_v1.0.xsl',
    'StyleSheetNE' => $PATH['XSL'] . 'NE_v1.0.xsl',
    'StyleSheetNS' => $PATH['XSL'] . 'NS_v1.0.xsl',
    'StyleSheetRC' => $PATH['XSL'] . 'RC_v1.0.xsl',
    'StyleSheetRS' => $PATH['XSL'] . 'RS_v1.0.xsl',
    'StyleSheetSE' => $PATH['XSL'] . 'SE_v1.0.xsl',
];
